### PR TITLE
ENH: V1.0.0

### PR DESCRIPTION
**Pull request by AdamTheisen**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by AdamTheisen** [comment]
@conda-forge-admin, please rerender

**Comment by zssherman** [comment]
Failure makes no sense, couldn't import TimeSeriesDisplay for .timeseriesdisplay, yet all other plotting modules look fine as well as timeseriesdisplay.

**Comment by zssherman** [comment]
And why do the unitests pass in our CI

**Comment by zssherman** [comment]
Rerunning the tests to see if this is some weird fluke

**Comment by AdamTheisen** [comment]
Yanked the pypi due to issues with the tar file that was uploaded. Going to close this pr

**Pull request closed without merging**
