### PR TITLE
ACT 0.5.0

### PR DESCRIPTION
**Pull request by AdamTheisen**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Review by zssherman — APPROVED** [review]
No updates from the rerender? Besides that looks good to me!

**Comment by AdamTheisen** [comment]
@conda-forge-admin, please rerender

**Comment by zssherman** [comment]
Hmm one of the tests failed, FAILED tests/test_retrievals.py::test_calculate_sirs_variable - AttributeErro...
Wish it would give more info...

**Comment by zssherman** [comment]
Oops nvm astral has no attribute observer

**Comment by zssherman** [comment]
Not seeing any changes to the repo with regards to observer

**Comment by zssherman** [comment]
@Looks like its installing the wrong version of astral a conda-forge version 1.9.2 when it should be a 2.2 the 1.9.2 version i had didn't have those classes, think you mentioned it before but the pypi version is way ahead for some reason.

**Comment by zssherman** [comment]
@AdamTheisen Yeah there 2 version increment versions or more recent versions are sitting in limbo on their feedstock.

**Comment by zssherman** [comment]
Ah and I see you opened an issue on their page, apologizes for the repetitiveness

**Comment by AdamTheisen** [comment]
@zssherman sorry, ran out to get the kids.  Yep, I'll have to go back and account for the dual astral versions.  It's somewhat of a pain but not sure if there's a way around at the moment

**Comment by zssherman** [comment]
And from reading, there doesn't seem to be a good way to set the pypi dependency for astral instead of conda-forge.

**Comment by AdamTheisen** [comment]
If you look at geo_utils.py in the utils area you can see what I had to do for a workaround

**Comment by AdamTheisen** [comment]
Got a fix in place and doing the PR now

**Comment by AdamTheisen** [comment]
Closing this out as we will need to do 0.5.1

**Pull request closed without merging**
